version: "3.7"
services:

  api:
    build:
      context: ./api
      dockerfile: ./dockerfile.apache+php8
    depends_on:
      - database
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./api
        target: /var/www
      - /dev/null:/var/www/.env.local
      - /dev/null:/var/www/.env.test.local

  web:
    build:
      context: ./web
      dockerfile: ./dockerfile.node+next
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - ./web:/usr/src

  database:
    build:
      context: ./database
      dockerfile: ./dockerfile.mysql8
    ports:
      - target: 3306
        published: 5306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: symfony-hotel
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: a3dcb4d229de6fde0db5686dee47145d

volumes:
  symfony-hotel: