security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        App\Entity\Employee:
            algorithm: auto
        
        App\Entity\Guest:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        employee_provider:
          entity:
            class: App\Entity\Employee
            property: uuid

        guest_provider:
          entity:
            class: App\Entity\Guest
            property: id
        
        users_provider:
          chain:
            providers: ["employee_provider", "guest_provider"]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            provider: users_provider
            user_checker: App\Security\GuestIsCheckInChecker

            json_login:
              check_path: /api/token
              username_path: login
              password_path: password
              success_handler: lexik_jwt_authentication.handler.authentication_success
              failure_handler: lexik_jwt_authentication.handler.authentication_failure
            
            jwt: ~
            
            #custom_authenticators:
            #  - App\Security\GuestAuthenticator
            
            logout: 
              path: /logout
            
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
      - { path: ^/api, roles: PUBLIC_ACCESS }
      - { path: ^/api/token, roles: PUBLIC_ACCESS }
      - { path: ^/, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
