import type { NextPage } from 'next';
import Head from 'next/head'
import Header from "./fragments/header";
import Nav from "./fragments/nav";
import Footer from "./fragments/footer";
import style from "./layoutBase.module.scss";

type LayoutBaseProps =
{
	children: React.ReactNode;
}

const LayoutBase = ({children}: LayoutBaseProps) : JSX.Element => 
{
	return (
		<>
			<Head>
				<title>NoName hotel</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="initial-scale=1, width=device-width" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<Header />
			<Nav />
			<main className={style.main}>{ children }</main>
			<Footer />
		</>
	)
}

export default LayoutBase;