import type { NextPage } from 'next';
import { useContext } from 'react';
import Head from 'next/head'
import Header from "./fragments/header";
import Nav from "./fragments/nav";
import Footer from "./fragments/footer";
import style from "./layoutBase.module.scss";
import AuthenticationContext from '../services/AuthenticationContext';

type LayoutBaseProps =
{
	children: React.ReactNode;
}

const LayoutBase = ({children}: LayoutBaseProps) : JSX.Element => 
{
	const {isAuthenticated} = useContext(AuthenticationContext);
	
	return (
		<>
			<Head>
				<title>NoName hotel</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="initial-scale=1, width=device-width" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			
			<Header />
			<Nav />
			<div>is: {isAuthenticated && "is indded"}</div>
			<main className={style.main}>{ children }</main>
			<Footer />
		</>
	)
}

export default LayoutBase;