import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<header className={styles.header} >
				<a className={styles.headerLink} href="/">
					<img src="/logo.png" alt="logo" />
				</a>
			</header>
			
			<nav className={styles.nav} >
				<div className={styles.navDiv}>
					<a className={styles.navLink} href="/rooms">
						<div className={styles.navLinkMain} >Pokoje</div>
						<div className={styles.navLinkSub} >standard &amp; ceny</div>
					</a>
				</div>
				<div className={styles.navDiv}>
					<a className={styles.navLink} href="/conferences">
						<div className={styles.navLinkMain} >Konferencje</div>
						<div className={styles.navLinkSub} >infrastruktura &amp; dostępność</div>
					</a>
				</div>
				<div className={styles.navDiv}>
					<a className={styles.navLink} href="/recreation">
						<div className={styles.navLinkMain}>Rekreacja</div>
						<div className={styles.navLinkSub}>spa &amp; basen</div>
					</a>
				</div>
				<div className={styles.navDiv}>
					<a className={styles.navLink} href="/contact">
						<div className={styles.navLinkMain}>Kontakt</div>
						<div className={styles.navLinkSub}>mapa &amp; telefon</div>
					</a>
				</div>
			</nav>
			
			<main className={styles.main}>
				<form>
					<input type="text" name="checkInAt" value="checkInAt" />
					<input type="text" name="checkInAt" value="checkInAt" />
					<input type="text" name="checkInAt" value="checkInAt" />
					<input type="text" name="checkInAt" value="checkInAt" />
				</form>
			</main>

			<footer className={styles.footer}>
				<section className={styles.footerLeft}>
					<div>Hotel NoName</div>
					<div>© 2021</div>
				</section>
				<img className={styles.footerLogo} src="/logo_small.png" alt="Small logo in footer"/>
				<section className={styles.footerRight}>
					<div>ul. Ulica 23</div>
					<div>00-000 Kraków, Polska</div>
					<div>tel. +48 00 000 00 00</div>
				</section>
			</footer>
		</div>
	)
}

export default Home