FROM php:8-apache
# enable mod_rewrite 
RUN a2enmod rewrite 
# install nessessary pdo extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql
COPY ./docker/apache.conf /etc/apache2/sites-enabled/000-default.conf
COPY . /var/www