FROM node:alpine

# create directory where our application will be run
RUN mkdir -p /usr/src
WORKDIR /usr/src

# copy our files into directory
COPY . /usr/src

# install dependences
RUN npm install
RUN npm install --save-dev @swc/cli @swc/core @swc/core-linux-musl

EXPOSE 3000
ENTRYPOINT ["npm", "run" ,"dev"]